name: reviewdog
on: [pull_request]

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: doc/source/data/getting-started.rst
          fail_on_error: true
          # Error on introduced changes only.
          filter_mode: added
          level: warning
